### ISSUE TITLE
Deprecate and migrate to gatsby repo

### ISSUE THREAD

**Issue by jondubin** [jondubin/gatsby-source-rss#4]
@KyleAMathews asked us to move this into the Gatsby Repo (https://github.com/gatsbyjs/gatsby/tree/master/packages) to unify the Gatsby ecosystem. @andrioid What do you think? I can go ahead and do this if you're on board.

**Comment by andrioid** [comment]
Sounds good to me!

**Comment by andrioid** [comment]
Is there any update on this? Something I can do to help?

**Comment by KyleAMathews** [comment]
Wait, I said that? Haha I might of but please remind me?

**Comment by jondubin** [comment]
@KyleAMathews I believe early on you said that you wanted all the Gatsby packages to live in the same repo, as an experiment. Does that ring any bells? I might be mistaken as well

**Comment by KyleAMathews** [comment]
Ah I might have said that :-)

But... definitely don't want that any more. There's far more plugins that need built than I can help maintain. I like having critical ones in the main repo and ones used in e.g. gatsbyjs.org or other key community properties but beyond that, totally great people having properties out here.

**Comment by jondubin** [comment]
Ok sounds good :-)
